### ISSUE TITLE
Multiple selections only affecting last

### ISSUE THREAD

**Issue by timtribers** [dlasky/grunt-dom-massager#6]
Hi,

I have been using this Grunt task for ages very successfully - thx.

But, just recently have been chasing a very odd problem.  if I have a simple class selector that matches multiple nodes, the action I specify is only working on the last one.

So, given this markup in test.html:

```
        <div class="me">One</div>
        <div class="you">Two</div>
        <div class="me">Three</div>
        <div class="you">Four</div>
        <div class="me">Five</div>
        <div class="you">Six</div>
```

and this dom-massager config in my gruntfile.js:

```
    dom_massager:{
      write_test: {
        options: {
          writeDom:true,
          selectors: {
            ".me": {
              action:"remove"
            },
            ".you": {
              action:"append",
              input:["<a href='blah'></a>"]
            }
          }
        },
        files: {
          'tmp/': ['test.html'],
        },
      }
    }

```

I get the result:

```

        <div class="you">Two</div>

        <div class="you">Four</div>

        <div class="you">Six<a href="blah"></a></div>

```

The **remove** has picked up all occurrences, but the **append** only the last.  The same happens with **prepend**.

Am I going mad and missing something obvious?  Or has cheerio updated and broken things, or what?

**Comment by dlasky** [comment]
So the cheerio version in this is .11 which is pretty old. I can try updating it to .22

the actual call is just passthrough though:

https://github.com/dlasky/grunt-dom-massager/blob/master/tasks/dom_massager.js#L61

Its been a long time since i wrote this but looking at it I think the actual selector handling couldn't be causing this.

(sorry for the late reply, somehow got unsubbed from this repo)

edit: found the upstream bug: https://github.com/cheeriojs/cheerio/issues/662

**Comment by dlasky** [comment]
Resolved in https://github.com/dlasky/grunt-dom-massager/commit/7a757862fc86b2f392f976f669ec8ec5f0c7cd16
